// flow-typed signature: 93386c354219775c8b960d6d50dacd55
// flow-typed version: <<STUB>>/@types/chai_v^4.0.4/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/chai'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/chai' {
  declare module.exports: any;
}
