// flow-typed signature: b05b7f157357b574ffc23599eab88e01
// flow-typed version: <<STUB>>/@types/classnames_v^2.2.3/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/classnames'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/classnames' {
  declare module.exports: any;
}
