// flow-typed signature: 1735d50650d748e5a582877d798b78cc
// flow-typed version: <<STUB>>/@types/express_v^4.0.39/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/express'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/express' {
  declare module.exports: any;
}
