// flow-typed signature: ebf5da1aa0b06f97b8d41b0a77c7ce43
// flow-typed version: <<STUB>>/@types/jquery_v^3.2.16/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/jquery'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/jquery' {
  declare module.exports: any;
}
