// flow-typed signature: e0c5a6627e17b841c72c7aef4a46db7a
// flow-typed version: <<STUB>>/@types/mocha_v^2.2.44/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/mocha'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/mocha' {
  declare module.exports: any;
}
