// flow-typed signature: 4cabe323187e256208e0c2e2531d9d4d
// flow-typed version: <<STUB>>/@types/prop-types_v^15.5.2/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/prop-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/prop-types' {
  declare module.exports: any;
}
