// flow-typed signature: 6854dd086a63d97415eb31659e8fc6cc
// flow-typed version: <<STUB>>/@types/react-bootstrap_v^0.31.6/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-bootstrap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-bootstrap' {
  declare module.exports: any;
}
