// flow-typed signature: 77a564d901d25036e27dbb2dae7eeada
// flow-typed version: <<STUB>>/loadable-components_v^1.4.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'loadable-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'loadable-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'loadable-components/babel' {
  declare module.exports: any;
}

declare module 'loadable-components/dist/loadable-components.babel.cjs' {
  declare module.exports: any;
}

declare module 'loadable-components/dist/loadable-components.cjs' {
  declare module.exports: any;
}

declare module 'loadable-components/dist/loadable-components.es' {
  declare module.exports: any;
}

declare module 'loadable-components/dist/loadable-components' {
  declare module.exports: any;
}

declare module 'loadable-components/dist/loadable-components.min' {
  declare module.exports: any;
}

declare module 'loadable-components/dist/loadable-components.server.cjs' {
  declare module.exports: any;
}

declare module 'loadable-components/server' {
  declare module.exports: any;
}

declare module 'loadable-components/src/__fixtures__/babel/basic/actual' {
  declare module.exports: any;
}

declare module 'loadable-components/src/__fixtures__/babel/basic/expected' {
  declare module.exports: any;
}

declare module 'loadable-components/src/__fixtures__/babel/multiple-imports/actual' {
  declare module.exports: any;
}

declare module 'loadable-components/src/__fixtures__/babel/multiple-imports/expected' {
  declare module.exports: any;
}

declare module 'loadable-components/src/__fixtures__/babel/options/actual' {
  declare module.exports: any;
}

declare module 'loadable-components/src/__fixtures__/babel/options/expected' {
  declare module.exports: any;
}

declare module 'loadable-components/src/__fixtures__/Book' {
  declare module.exports: any;
}

declare module 'loadable-components/src/__fixtures__/Books' {
  declare module.exports: any;
}

declare module 'loadable-components/src/__fixtures__/Dummy' {
  declare module.exports: any;
}

declare module 'loadable-components/src/__fixtures__/Routes' {
  declare module.exports: any;
}

declare module 'loadable-components/src/babel' {
  declare module.exports: any;
}

declare module 'loadable-components/src/babel.test' {
  declare module.exports: any;
}

declare module 'loadable-components/src/componentTracker' {
  declare module.exports: any;
}

declare module 'loadable-components/src/componentTracker.test' {
  declare module.exports: any;
}

declare module 'loadable-components/src/config' {
  declare module.exports: any;
}

declare module 'loadable-components/src/config.test' {
  declare module.exports: any;
}

declare module 'loadable-components/src/constants' {
  declare module.exports: any;
}

declare module 'loadable-components/src/getState' {
  declare module.exports: any;
}

declare module 'loadable-components/src/getState.test' {
  declare module.exports: any;
}

declare module 'loadable-components/src/index' {
  declare module.exports: any;
}

declare module 'loadable-components/src/loadable' {
  declare module.exports: any;
}

declare module 'loadable-components/src/loadable.test' {
  declare module.exports: any;
}

declare module 'loadable-components/src/loadComponents' {
  declare module.exports: any;
}

declare module 'loadable-components/src/loadComponents.test' {
  declare module.exports: any;
}

declare module 'loadable-components/src/server/DeferredState' {
  declare module.exports: any;
}

declare module 'loadable-components/src/server/DeferredState.test' {
  declare module.exports: any;
}

declare module 'loadable-components/src/server/index' {
  declare module.exports: any;
}

declare module 'loadable-components/src/server/index.test' {
  declare module.exports: any;
}

declare module 'loadable-components/src/utils/resolveModuleDefault' {
  declare module.exports: any;
}

declare module 'loadable-components/src/utils/resolveModuleDefault.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'loadable-components/babel.js' {
  declare module.exports: $Exports<'loadable-components/babel'>;
}
declare module 'loadable-components/dist/loadable-components.babel.cjs.js' {
  declare module.exports: $Exports<'loadable-components/dist/loadable-components.babel.cjs'>;
}
declare module 'loadable-components/dist/loadable-components.cjs.js' {
  declare module.exports: $Exports<'loadable-components/dist/loadable-components.cjs'>;
}
declare module 'loadable-components/dist/loadable-components.es.js' {
  declare module.exports: $Exports<'loadable-components/dist/loadable-components.es'>;
}
declare module 'loadable-components/dist/loadable-components.js' {
  declare module.exports: $Exports<'loadable-components/dist/loadable-components'>;
}
declare module 'loadable-components/dist/loadable-components.min.js' {
  declare module.exports: $Exports<'loadable-components/dist/loadable-components.min'>;
}
declare module 'loadable-components/dist/loadable-components.server.cjs.js' {
  declare module.exports: $Exports<'loadable-components/dist/loadable-components.server.cjs'>;
}
declare module 'loadable-components/server.js' {
  declare module.exports: $Exports<'loadable-components/server'>;
}
declare module 'loadable-components/src/__fixtures__/babel/basic/actual.js' {
  declare module.exports: $Exports<'loadable-components/src/__fixtures__/babel/basic/actual'>;
}
declare module 'loadable-components/src/__fixtures__/babel/basic/expected.js' {
  declare module.exports: $Exports<'loadable-components/src/__fixtures__/babel/basic/expected'>;
}
declare module 'loadable-components/src/__fixtures__/babel/multiple-imports/actual.js' {
  declare module.exports: $Exports<'loadable-components/src/__fixtures__/babel/multiple-imports/actual'>;
}
declare module 'loadable-components/src/__fixtures__/babel/multiple-imports/expected.js' {
  declare module.exports: $Exports<'loadable-components/src/__fixtures__/babel/multiple-imports/expected'>;
}
declare module 'loadable-components/src/__fixtures__/babel/options/actual.js' {
  declare module.exports: $Exports<'loadable-components/src/__fixtures__/babel/options/actual'>;
}
declare module 'loadable-components/src/__fixtures__/babel/options/expected.js' {
  declare module.exports: $Exports<'loadable-components/src/__fixtures__/babel/options/expected'>;
}
declare module 'loadable-components/src/__fixtures__/Book.js' {
  declare module.exports: $Exports<'loadable-components/src/__fixtures__/Book'>;
}
declare module 'loadable-components/src/__fixtures__/Books.js' {
  declare module.exports: $Exports<'loadable-components/src/__fixtures__/Books'>;
}
declare module 'loadable-components/src/__fixtures__/Dummy.js' {
  declare module.exports: $Exports<'loadable-components/src/__fixtures__/Dummy'>;
}
declare module 'loadable-components/src/__fixtures__/Routes.js' {
  declare module.exports: $Exports<'loadable-components/src/__fixtures__/Routes'>;
}
declare module 'loadable-components/src/babel.js' {
  declare module.exports: $Exports<'loadable-components/src/babel'>;
}
declare module 'loadable-components/src/babel.test.js' {
  declare module.exports: $Exports<'loadable-components/src/babel.test'>;
}
declare module 'loadable-components/src/componentTracker.js' {
  declare module.exports: $Exports<'loadable-components/src/componentTracker'>;
}
declare module 'loadable-components/src/componentTracker.test.js' {
  declare module.exports: $Exports<'loadable-components/src/componentTracker.test'>;
}
declare module 'loadable-components/src/config.js' {
  declare module.exports: $Exports<'loadable-components/src/config'>;
}
declare module 'loadable-components/src/config.test.js' {
  declare module.exports: $Exports<'loadable-components/src/config.test'>;
}
declare module 'loadable-components/src/constants.js' {
  declare module.exports: $Exports<'loadable-components/src/constants'>;
}
declare module 'loadable-components/src/getState.js' {
  declare module.exports: $Exports<'loadable-components/src/getState'>;
}
declare module 'loadable-components/src/getState.test.js' {
  declare module.exports: $Exports<'loadable-components/src/getState.test'>;
}
declare module 'loadable-components/src/index.js' {
  declare module.exports: $Exports<'loadable-components/src/index'>;
}
declare module 'loadable-components/src/loadable.js' {
  declare module.exports: $Exports<'loadable-components/src/loadable'>;
}
declare module 'loadable-components/src/loadable.test.js' {
  declare module.exports: $Exports<'loadable-components/src/loadable.test'>;
}
declare module 'loadable-components/src/loadComponents.js' {
  declare module.exports: $Exports<'loadable-components/src/loadComponents'>;
}
declare module 'loadable-components/src/loadComponents.test.js' {
  declare module.exports: $Exports<'loadable-components/src/loadComponents.test'>;
}
declare module 'loadable-components/src/server/DeferredState.js' {
  declare module.exports: $Exports<'loadable-components/src/server/DeferredState'>;
}
declare module 'loadable-components/src/server/DeferredState.test.js' {
  declare module.exports: $Exports<'loadable-components/src/server/DeferredState.test'>;
}
declare module 'loadable-components/src/server/index.js' {
  declare module.exports: $Exports<'loadable-components/src/server/index'>;
}
declare module 'loadable-components/src/server/index.test.js' {
  declare module.exports: $Exports<'loadable-components/src/server/index.test'>;
}
declare module 'loadable-components/src/utils/resolveModuleDefault.js' {
  declare module.exports: $Exports<'loadable-components/src/utils/resolveModuleDefault'>;
}
declare module 'loadable-components/src/utils/resolveModuleDefault.test.js' {
  declare module.exports: $Exports<'loadable-components/src/utils/resolveModuleDefault.test'>;
}
