// flow-typed signature: 42b674de7f45d504b4c8773911e53fa1
// flow-typed version: <<STUB>>/superagent_v^3.0.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'superagent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'superagent' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'superagent/lib/client' {
  declare module.exports: any;
}

declare module 'superagent/lib/is-object' {
  declare module.exports: any;
}

declare module 'superagent/lib/node/agent' {
  declare module.exports: any;
}

declare module 'superagent/lib/node/index' {
  declare module.exports: any;
}

declare module 'superagent/lib/node/parsers/image' {
  declare module.exports: any;
}

declare module 'superagent/lib/node/parsers/index' {
  declare module.exports: any;
}

declare module 'superagent/lib/node/parsers/json' {
  declare module.exports: any;
}

declare module 'superagent/lib/node/parsers/text' {
  declare module.exports: any;
}

declare module 'superagent/lib/node/parsers/urlencoded' {
  declare module.exports: any;
}

declare module 'superagent/lib/node/response' {
  declare module.exports: any;
}

declare module 'superagent/lib/node/utils' {
  declare module.exports: any;
}

declare module 'superagent/lib/request-base' {
  declare module.exports: any;
}

declare module 'superagent/lib/request' {
  declare module.exports: any;
}

declare module 'superagent/superagent' {
  declare module.exports: any;
}

// Filename aliases
declare module 'superagent/lib/client.js' {
  declare module.exports: $Exports<'superagent/lib/client'>;
}
declare module 'superagent/lib/is-object.js' {
  declare module.exports: $Exports<'superagent/lib/is-object'>;
}
declare module 'superagent/lib/node/agent.js' {
  declare module.exports: $Exports<'superagent/lib/node/agent'>;
}
declare module 'superagent/lib/node/index.js' {
  declare module.exports: $Exports<'superagent/lib/node/index'>;
}
declare module 'superagent/lib/node/parsers/image.js' {
  declare module.exports: $Exports<'superagent/lib/node/parsers/image'>;
}
declare module 'superagent/lib/node/parsers/index.js' {
  declare module.exports: $Exports<'superagent/lib/node/parsers/index'>;
}
declare module 'superagent/lib/node/parsers/json.js' {
  declare module.exports: $Exports<'superagent/lib/node/parsers/json'>;
}
declare module 'superagent/lib/node/parsers/text.js' {
  declare module.exports: $Exports<'superagent/lib/node/parsers/text'>;
}
declare module 'superagent/lib/node/parsers/urlencoded.js' {
  declare module.exports: $Exports<'superagent/lib/node/parsers/urlencoded'>;
}
declare module 'superagent/lib/node/response.js' {
  declare module.exports: $Exports<'superagent/lib/node/response'>;
}
declare module 'superagent/lib/node/utils.js' {
  declare module.exports: $Exports<'superagent/lib/node/utils'>;
}
declare module 'superagent/lib/request-base.js' {
  declare module.exports: $Exports<'superagent/lib/request-base'>;
}
declare module 'superagent/lib/request.js' {
  declare module.exports: $Exports<'superagent/lib/request'>;
}
declare module 'superagent/superagent.js' {
  declare module.exports: $Exports<'superagent/superagent'>;
}
